name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: TEMP
      run: npm run docs
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
